exporters:
  otlphttp:
    logs_endpoint: http://victorialogs:9428/insert/opentelemetry/api/v1/push
  loki:
    endpoint: http://victorialogs:9428/insert/loki/api/v1/push
  elasticsearch:
    endpoints:
      - http://victorialogs:9428/insert/elasticsearch
receivers:
  filelog:
    include: [/tmp/logs/*.log]
    resource:
      region: us-east-1
service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [elasticsearch, loki, otlphttp]
